### ISSUE TITLE
VASim won't report for a simple automaton

### ISSUE THREAD

**Issue by rpr2pj** [tjt7a/VASim#1]
I was expecting VASim to report with report code 205 at index 4350.

[split_automata_426.anml.txt](https://github.com/tjt7a/VASim/files/9758933/split_automata_426.anml.txt)
[pro_input.input.zip](https://github.com/tjt7a/VASim/files/9758940/pro_input.input.zip)

**Comment by tjt7a** [comment]
Because the start state in the attached automaton file (split_automata_426.anml.txt) is a 'start-of-data' state, it will not match on the attached input file. If you convert the start state to a 'all-input' start state, it will.
